version: '3'

services:
  angular-app:
    build:
      context: .
      dockerfile: ./frontend/angular-app/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/angular-app/pataponto:/usr/src/app
    working_dir: /usr/src/app/angular-app
      

  flask-app:
    build:
      context: ./backend/flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./backend/flask-app:/usr/src/app
