version: '3'

services:
  angular-app:
    build:
      context: .
      dockerfile: ./frontend/angular-app/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/angular-app/pataponto:/usr/src/app
    working_dir: /usr/src/app/angular-app
    depends_on:
      - mysql
      

  flask-app:
    build:
      context: ./backend/flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./backend/flask-app:/usr/src/app
    depends_on:
      - mysql

  # TODO: mysql -u admin -padmin pataponto < setups.sql
  # init inserts is not working
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pataponto
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./db/mysql-scripts:/docker-entrypoint-initdb.d

